#!/usr/bin/env python3
"""
Prints a Home Assistant dashboard (raw YAML) for every kid in config.json:
one column per kid with a big "time left" number, status, every Mac's
state, and the controls (Allowed, Parent Override, budget, bonus).

Built-in cards only (markdown, tile, grid, vertical-stack), so it works on
older HA versions and needs nothing from HACS. Entity ids come from the
per-kid device's predictable names (e.g. number.<child>_daily_budget); the
per-Mac rows are found by pattern, so a new Mac shows up by itself.

Usage: make_ha_dashboard.py [path/to/config.json]
Paste the output into Settings > Dashboards > (new dashboard) > ⋮ >
Edit dashboard > ⋮ > Raw configuration editor.
Stdlib only, Python 3.8+ (runs with the system python3 the installer uses).
"""

from __future__ import annotations

import json
import sys

DEFAULT_CONFIG = "/Library/Application Support/ha-screen-agent/config.json"

# The kid's status card. KID is replaced with the child_name, NAME with a
# display name. Same effective-limit math as the budget blueprint:
# budget + min(bonus, max bonus), max bonus treated as 60 until set.
STATUS_TEMPLATE = r"""{%- macro hm(m) -%}
{%- if m >= 60 -%}{{ m // 60 }}h {{ '%02d' | format(m % 60) }}m{%- else -%}{{ m }}m{%- endif -%}
{%- endmacro -%}
{%- set used = states('sensor.KID_total_minutes_today') | int(0) -%}
{%- set budget = states('number.KID_daily_budget') -%}
{%- set bonus = states('number.KID_bonus_minutes') | int(0) -%}
{%- set maxb = states('number.KID_max_bonus_minutes') | int(60) -%}
{%- set applied = [bonus, maxb] | min -%}
## NAME
{% if budget | is_number -%}
{%- set limit = (budget | int(0)) + applied -%}
{%- set left = [limit - used, 0] | max -%}
# {{ hm(left) }} left
**Used {{ hm(used) }} of {{ hm(limit) }}**{{ ' (includes ' ~ applied ~ 'm bonus)' if applied > 0 else '' }}
{%- else %}
# No budget set
{%- endif %}

### {{ '✅ Allowed' if is_state('switch.KID_allowed', 'on') else '⛔ Blocked' }}{{ ' · 🛡️ Override' if is_state('switch.KID_parent_override', 'on') else '' }}
{% for s in states.sensor | selectattr('entity_id', 'search', '^sensor\\.KID_mac_.+_session_state$') | sort(attribute='entity_id') %}
{%- set dev = s.name | regex_findall('\\(([^)]+)\\)') | first | default(s.name) -%}
{%- set label = {'active': '🟢 in use', 'locked': '🔒 locked', 'backgrounded': '⚪ switched away', 'offline': '⚫ not logged in', 'unavailable': '⚫ Mac offline', 'unknown': '⚫ Mac offline'}.get(s.state, '❔ ' ~ s.state) %}
{{ dev }}: {{ label }}<br>
{%- endfor %}
"""


def display_name(child: str) -> str:
    """screentime_cj -> CJ, screentime_aaron -> Aaron, kiddo -> Kiddo."""
    short = child.rsplit("_", 1)[-1] or child
    return short.upper() if len(short) <= 2 else short.title()


def indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line else "" for line in text.splitlines())


def kid_column(child: str) -> str:
    status = STATUS_TEMPLATE.replace("KID", child).replace("NAME", display_name(child))
    tiles = [
        ("switch", "allowed", "Allowed"),
        ("switch", "parent_override", "Parent Override"),
        ("number", "daily_budget", "Daily Budget"),
        ("number", "bonus_minutes", "Bonus Minutes"),
        ("number", "max_bonus_minutes", "Max Bonus"),
    ]
    tile_yaml = "\n".join(
        f"          - type: tile\n"
        f"            entity: {domain}.{child}_{field}\n"
        f"            name: {name}"
        for domain, field, name in tiles
    )
    return (
        "      - type: vertical-stack\n"
        "        cards:\n"
        "          - type: markdown\n"
        "            content: |\n"
        f"{indent(status, 14)}\n"
        "          - type: grid\n"
        "            columns: 2\n"
        "            square: false\n"
        "            cards:\n"
        f"{indent(tile_yaml, 4)}\n"
    )


def build(config: dict) -> str:
    kids = [
        (e.get("child_name") or "").strip()
        for e in config.get("managed_users") or []
    ]
    kids = [k for k in kids if k]
    out = [
        "# Generated by scripts/make_ha_dashboard.py from config.json.",
        "title: Screen Time",
        "views:",
        "  - title: Screen Time",
        "    path: screen-time",
        "    icon: mdi:timer-sand",
        "    cards:",
    ]
    out.extend(kid_column(k) for k in kids)
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_CONFIG
    with open(path, "r", encoding="utf-8") as fh:
        sys.stdout.write(build(json.load(fh)))


if __name__ == "__main__":
    main()
